---
downloads: ~/.ansible-downloads/

# uses my own dotfiles role
configure_dotfiles: yes
# not yet
configure_sudoers: no
configure_terminal: no
configure_osx: no

homebrew_installed_packages:
  - mas
  - tree
  - wget
  - fontforge
  - tmux

homebrew_taps:
  - homebrew/core
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - choosy
  - resilio-sync
  - virtualbox
  - macvim
  - hammerspoon
  - flycut
  - dropbox
  - alfred
  - bartender
  - tunnelblick
  - caffeine
  - growlnotify
  - superduper
  - plex-media-player
  - spotify
  # manual
  # - istat-menus
  # - monosnap
  # - git-annex
  # not yet
  # - docker

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 803453959, name: "Slack" }
  - { id: 443987910, name: "1Password - Password Manager and Secure Wallet" }
  - { id: 975937182, name: "Fantastical 2 - Calendar and Reminders" }
  - { id: 540348655, name: "Monosnap" }
  - { id: 488566438, name: "aText" }
  - { id: 467939042, name: "Growl" }
  - { id: 496437906, name: "Shush - Microphone Manager" }
  - { id: 867299399, name: "OmniFocus 2" }
  - { id: 711830901, name: "OmniGraffle" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# TODO: manual steps
# * set up hosts file
# * mac stuff
#   * change dictation trigger
#   * make keyboard work with all controls
#   * hot corners for screensaver
#   * escape key for caps lock
#   * disable spotlight and finder search keymappings
#   * disable search on external drives
#   * use tap to click
#   * three finger drag
